version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

